 /*************************************
 * stm32_gpio_pinconfig.h
 * author: jan
 * last modifications: 
 * 
 * description: The behavior of each I/O pin is defined in this file, beside some other
 * macros used for the configuration of the GPIO ports.
 * Pins may be configured as inputs, outputs, be used as alternate function pins e.g. for
 * communication peripherals as USART, SPI etc.
 * Please see details below.
 **************************************/

#ifndef STM32_GPIO_PINCONFIG_H_
#define STM32_GPIO_PINCONFIG_H_

 /*Includes*********************************/

 /*Pin Configuration******************************/
/*===Example=====================================*/
//#define GPIOx_y_CONFIG_BEHAVIOUR input mode: ANALOG, FLOATING, PULLUP || output mode: GP_PPULL, GP_ODRAIN, AF_PPULL, AF_ODRAIN
//#define GPIOx_y_CONFIG_DIRECTION_SPEED INPUT, MHZ2, MHZ10, MHZ50			//input mode or output max.speed 2,10, 50 MHz
/*===============================================*/
#define ANALOG 0b00
#define FLOATING 0b01
#define PULLUP 0b10

#define GP_PPULL 0b00
#define GP_ODRAIN 0b01
#define AF_PPULL 0b10
#define AF_ODRAIN 0b11

#define INPUT 0b00
#define MHZ2 0b01
#define MHZ10 0b10
#define MHZ50 0b11
/*=====GPIO A==============================*/
#define GPIOA_0_CONFIG_BEHAVIOUR AF_PPULL
#define GPIOA_0_CONFIG_DIRECTION_SPEED MHZ50					//Timer 2 channel 1, PWM output

#define GPIOA_1_CONFIG_BEHAVIOUR AF_PPULL
#define GPIOA_1_CONFIG_DIRECTION_SPEED MHZ50					//Timer 2 channel 2, PWM output

#define GPIOA_2_CONFIG_BEHAVIOUR AF_PPULL
#define GPIOA_2_CONFIG_DIRECTION_SPEED MHZ50					//Timer 2 channel 3, PWM output

#define GPIOA_3_CONFIG_BEHAVIOUR AF_PPULL
#define GPIOA_3_CONFIG_DIRECTION_SPEED MHZ50					//Timer 2 channel 4, PWM output

#define GPIOA_4_CONFIG_BEHAVIOUR FLOATING
#define GPIOA_4_CONFIG_DIRECTION_SPEED INPUT

#define GPIOA_5_CONFIG_BEHAVIOUR AF_PPULL						//SPI1_SCK
#define GPIOA_5_CONFIG_DIRECTION_SPEED MHZ50

#define GPIOA_6_CONFIG_BEHAVIOUR FLOATING						//SPI1 MISO
#define GPIOA_6_CONFIG_DIRECTION_SPEED INPUT

#define GPIOA_7_CONFIG_BEHAVIOUR AF_PPULL						//SPI1_MOSI
#define GPIOA_7_CONFIG_DIRECTION_SPEED MHZ50

#define GPIOA_8_CONFIG_BEHAVIOUR FLOATING						//Timer 1 channel 1 capture input (used to measure the ppm output of a RC receiver)
#define GPIOA_8_CONFIG_DIRECTION_SPEED INPUT

#define GPIOA_9_CONFIG_BEHAVIOUR AF_PPULL						//USART1_TX
#define GPIOA_9_CONFIG_DIRECTION_SPEED MHZ50

#define GPIOA_10_CONFIG_BEHAVIOUR FLOATING
#define GPIOA_10_CONFIG_DIRECTION_SPEED INPUT

#define GPIOA_11_CONFIG_BEHAVIOUR FLOATING
#define GPIOA_11_CONFIG_DIRECTION_SPEED INPUT					//CAN1_RX

#define GPIOA_12_CONFIG_BEHAVIOUR AF_PPULL
#define GPIOA_12_CONFIG_DIRECTION_SPEED MHZ50					//CAN1_TX

#define GPIOA_13_CONFIG_BEHAVIOUR FLOATING
#define GPIOA_13_CONFIG_DIRECTION_SPEED INPUT

#define GPIOA_14_CONFIG_BEHAVIOUR FLOATING
#define GPIOA_14_CONFIG_DIRECTION_SPEED INPUT

#define GPIOA_15_CONFIG_BEHAVIOUR FLOATING
#define GPIOA_15_CONFIG_DIRECTION_SPEED INPUT

/*=====GPIO B==============================*/
#define GPIOB_0_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_0_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_1_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_1_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_2_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_2_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_3_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_3_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_4_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_4_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_5_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_5_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_6_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_6_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_7_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_7_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_8_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_8_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_9_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_9_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_10_CONFIG_BEHAVIOUR AF_PPULL				//UART3 TX
#define GPIOB_10_CONFIG_DIRECTION_SPEED MHZ50

#define GPIOB_11_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_11_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_12_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_12_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_13_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_13_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_14_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_14_CONFIG_DIRECTION_SPEED INPUT

#define GPIOB_15_CONFIG_BEHAVIOUR FLOATING
#define GPIOB_15_CONFIG_DIRECTION_SPEED INPUT

/*=====GPIO C==============================*/
#define GPIOC_0_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_0_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_1_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_1_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_2_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_2_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_3_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_3_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_4_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_4_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_5_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_5_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_6_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_6_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_7_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_7_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_8_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_8_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_9_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_9_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_10_CONFIG_BEHAVIOUR GP_PPULL
#define GPIOC_10_CONFIG_DIRECTION_SPEED MHZ50

#define GPIOC_11_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_11_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_12_CONFIG_BEHAVIOUR GP_PPULL				//connected to Olimex H103 test board status LED
#define GPIOC_12_CONFIG_DIRECTION_SPEED MHZ50

#define GPIOC_13_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_13_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_14_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_14_CONFIG_DIRECTION_SPEED INPUT

#define GPIOC_15_CONFIG_BEHAVIOUR FLOATING
#define GPIOC_15_CONFIG_DIRECTION_SPEED INPUT

/*=====GPIO D==============================*/
#define GPIOD_0_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_0_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_1_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_1_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_2_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_2_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_3_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_3_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_4_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_4_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_5_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_5_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_6_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_6_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_7_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_7_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_8_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_8_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_9_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_9_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_10_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_10_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_11_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_11_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_12_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_12_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_13_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_13_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_14_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_14_CONFIG_DIRECTION_SPEED INPUT

#define GPIOD_15_CONFIG_BEHAVIOUR FLOATING
#define GPIOD_15_CONFIG_DIRECTION_SPEED INPUT

/*=====GPIO E==============================*/
#define GPIOE_0_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_0_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_1_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_1_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_2_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_2_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_3_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_3_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_4_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_4_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_5_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_5_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_6_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_6_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_7_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_7_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_8_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_8_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_9_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_9_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_10_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_10_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_11_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_11_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_12_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_12_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_13_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_13_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_14_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_14_CONFIG_DIRECTION_SPEED INPUT

#define GPIOE_15_CONFIG_BEHAVIOUR FLOATING
#define GPIOE_15_CONFIG_DIRECTION_SPEED INPUT

/*=====GPIO F==============================*/
#define GPIOF_0_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_0_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_1_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_1_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_2_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_2_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_3_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_3_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_4_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_4_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_5_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_5_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_6_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_6_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_7_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_7_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_8_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_8_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_9_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_9_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_10_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_10_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_11_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_11_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_12_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_12_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_13_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_13_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_14_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_14_CONFIG_DIRECTION_SPEED INPUT

#define GPIOF_15_CONFIG_BEHAVIOUR FLOATING
#define GPIOF_15_CONFIG_DIRECTION_SPEED INPUT

/*=====GPIO G==============================*/
#define GPIOG_0_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_0_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_1_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_1_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_2_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_2_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_3_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_3_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_4_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_4_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_5_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_5_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_6_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_6_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_7_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_7_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_8_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_8_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_9_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_9_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_10_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_10_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_11_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_11_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_12_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_12_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_13_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_13_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_14_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_14_CONFIG_DIRECTION_SPEED INPUT

#define GPIOG_15_CONFIG_BEHAVIOUR FLOATING
#define GPIOG_15_CONFIG_DIRECTION_SPEED INPUT


#endif /* STM32_GPIO_PINCONFIG_H_ */
